[[introduction]]
Introduction
------------

This repository is a demo for using Netdisco in a
https://cumulusnetworks.com/products/cumulus-vx/[Cumulus] VX
https://github.com/CumulusNetworks/cldemo-vagrant[Network].

[[network-build]]
Preparation
-----------

Before running this demo, install
https://www.virtualbox.org/wiki/Downloads[VirtualBox] and
https://www.vagrantup.com/downloads.html[Vagrant].

An instance of Netdisco backend inside the network is configured to connect to
a PostgreSQL database running on your host computer system.

You will need to edit the Vagrantfile included to change the
`NETDISCO_DB_NAME` and `NETDISCO_DB_USER` for your system. Do not change
`NETDISCO_DB_HOST`.

[[startup]]
Startup
-------

....
git clone --recurse-submodules https://github.com/netdisco/cumulus-netdisco-demo.git
vagrant up && vagrant up --provision ssh-mgmt-server
....

[[access-netdisco-backend]]
Access Netdisco Backend
-----------------------

Should you wish to visit the backend docker container:

....
vagrant ssh
docker exec -it netdisco-backend sh
....

The Netdisco configuration is in `./environments` as usual.

[[caveats]]
Caveats
-------

You will need to run the web frontend on your workstation. Obviously,
this does not share configuration with the backend docker container
running on `oob-mgm-server`.

So far, SNMP::Info is not doing a good job with the Cumulus platform.
This will not be hard to fix.
