# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "oob-mgmt-server" do |device|
    device.vm.provision "docker" do |d|
      d.run "netdisco-backend",
        args:  "-e NETDISCO_DB_NAME=cumulus -e NETDISCO_DB_USER=oliver -e NETDISCO_DB_HOST=10.0.2.2",
        image: "netdisco/netdisco:latest-backend"
    end
  end
end
