- hosts: network
  become: yes
  tasks:
    - name: Configure SNMP service on all network devices
      nclu:
        atomic: true
        description: "Ansible - enable SNMP service"
        commands:
          - add snmp-server listening-address all
          - add snmp-server readonly-community public access any oid .1
          - add snmp-server system-location {{ group_names[0] }}
          - add snmp-server system-name {{ ansible_hostname }}
    - name: set SNMP sysServices
      lineinfile:
        path: /etc/snmp/snmpd.conf
        regexp: '^sysServices '
        line: 'sysServices 78'
    - name: copy fixed ieee8023_lag_pp.py
      copy:
        src: src/usr/share/snmp/ieee8023_lag_pp.py
        dest: /usr/share/snmp/ieee8023_lag_pp.py
        owner: root
        mode: 0755
    - name: update lldpd default args
      template:
        src: src/etc/default/lldpd.j2
        dest: /etc/default/lldpd
    - name: enable snmpd
      command: systemctl enable snmpd.service
    - name: start snmpd
      command: systemctl restart snmpd.service
    - name: restart lddpd
      command: systemctl restart lldpd.service
- hosts: left_servers
  become: yes
  tasks:
    - name: keep server in gateway ARP cache
      cron:
        name: prime gateway ARP cache
        job: "ping -n -c2 -BI uplink 172.16.1.1"
- hosts: right_servers
  become: yes
  tasks:
    - name: keep server in gateway ARP cache
      cron:
        name: prime gateway ARP cache
        job: "ping -n -c2 -BI uplink 172.16.1.2"
